pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // O JitPack precisa estar aqui para o app encontrar o JsEvaluator
        maven { url 'https://jitpack.io' } 
    }
}
rootProject.name = "Pinhoabacaxi Musics"
include ':app'
include ':kotlinYoutubeExtractor'
